name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ghc96, ghc98, ghc910]
    steps:
      - uses: actions/checkout@v3.5.3
        name: Checkout
      - uses: cachix/install-nix-action@v22
        name: Install Nix
      - uses: cachix/cachix-action@v12
        name: Set up Cachix
        with:
          name: awakesecurity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build --attr grpc-haskell --argstr ghc ${{ matrix.ghc }}
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        ghc: [ghc96, ghc98, ghc910]
    steps:
      - uses: actions/checkout@v3.5.3
        name: Checkout
      - uses: cachix/install-nix-action@v22
        name: Install Nix
      - uses: cachix/cachix-action@v12
        name: Set up Cachix
        with:
          name: awakesecurity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build --attr grpc-haskell-no-tests --argstr ghc ${{ matrix.ghc }}
